// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwaggerTest.Services.Contexts;

#nullable disable

namespace SwaggerTest.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SwaggerTest.Data.DataTypeTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Byte")
                        .HasColumnType("tinyint");

                    b.Property<double>("Currency")
                        .HasColumnType("float");

                    b.Property<decimal>("Decimal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Double")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Float")
                        .HasColumnType("real");

                    b.Property<byte>("GenderByteEnum")
                        .HasColumnType("tinyint");

                    b.Property<int>("GenderEnum")
                        .HasColumnType("int");

                    b.Property<int>("Int")
                        .HasColumnType("int");

                    b.Property<string>("LimitNvarchar")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Long")
                        .HasColumnType("bigint");

                    b.Property<string>("MaxNvarchar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("SByte")
                        .HasColumnType("smallint");

                    b.Property<short>("Short")
                        .HasColumnType("smallint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UInt")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ULong")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("USHort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DataTypeTables");
                });
#pragma warning restore 612, 618
        }
    }
}
